node {

  // job
  try {
    stage('build') {
      println('1 - So far so good...')
    }
    stage('test') {
      println('2 - A test has failed!')
      sh 'exit 1'
    }
  } catch(e) {
    // mark build as failed
    currentBuild.result = "FAILURE";
    // set variables
    def subject = "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} ${currentBuild.result}"
    def content = '${JELLY_SCRIPT,template="html"}'

    // send email
    emailext body: content, replyTo: '$DEFAULT_REPLYTO', attachLog: true, recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']], subject: subject

    // mark current build as a failure and throw the error
    throw e;
  }
}
